### ISSUE TITLE
[DOC] Update general application Readme.md file

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#120]
## Reason
Since they gave us the skeleton of the application to now, we have made many changes, we need to update the [readme of the application](https://github.com/Arquisoft/wiq_es1c/blob/master/README.md) so that from github we know how to launch the application and understand the main modules into which it is divided.
## TO DO´s
- Wiq_es1c modules description
- Wiq_es1c project description
- Quick start guide > Starting Component by component

**Comment by Manueluz** [comment]
Im pretty sure this one is done
