### ISSUE TITLE
[APP] User profile

### ISSUE THREAD

**Issue by RubenFern** [Arquisoft/wiq_es1c#14]
Los usuarios podrán visualizar en la pantalla de su perfil su histórico de participación. Es decir, número de veces que ha jugado, preguntas falladas/acertadas, tiempo medio de resupesta, etc.

**Comment by gs-Manuel** [comment]
Closed by new Issue with same task: [issue 126](https://github.com/Arquisoft/wiq_es1c/issues/126)
