### ISSUE TITLE
[APP] Create Game Modes

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#181]
- [x] only Flag questions
- [x] only One Category questions
- [x] against the clock game mode

**Comment by 22Noel** [comment]
- [ ] sudden death gamemode

**Comment by 22Noel** [comment]
We've decided that gamemodes now affect how the game its played, not the type of questions the player is asked, so only flags gamemode will be replaced by tags functionality

**Comment by 22Noel** [comment]
Delayed to sprint 4
