### ISSUE TITLE
[APP] Improve Usability

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#183]
- [ ] Make a dynamic background of WebApp: look at [30+ css animated background](https://freefrontend.com/css-animated-backgrounds/)
- [ ] Add titles to nav buttons and margin color css
- [ ] Add label in footer showing copyrights reserved
- [ ] Add About us explaining who are us and linking the [Github Repository](https://github.com/Arquisoft/wiq_es1c)
- [ ] Fix tag buttons in white mode => just modify the margin color

**Comment by Manueluz** [comment]
Fix ligth mode!!

**Comment by Manueluz** [comment]
And improve overall CSS
