### ISSUE TITLE
[DOC] Read frontend tutorials

### ISSUE THREAD

**Issue by Manueluz** [Arquisoft/wiq_es1c#5]

**Comment by Manueluz** [comment]
# Tutoriales Frontend
## React - JS + HTML
(Tecnologia frontend escogida en el Draft 2 - Issue #34 )

Primero antes de ver ningun tutorial, es necesario saber que es react, este video lo explica en 100 segundos:

- [React in 100 seconds - EN](https://www.youtube.com/watch?v=Tn6-PIqc4UM)

Ahora ya podemos empezar a ver tutoriales de react:

- [React tutorial para principiantes 10 minutos - ES](https://www.youtube.com/watch?v=wGxDfSWC4Ww)
- ***[React tutorial Kahoot clon ;) - EN](https://www.youtube.com/watch?v=DJxM76m4eP0&list=PLEVTJcDnFDm9lpEEHTftRa9JSRV4jY_p9)***
## Tailwind - CSS
(Tecnologia frontend escogida en el Draft 2 - Issue #34 )

Primero antes de ver ningun tutorial, es necesario saber que es Tailwind CSS, este video lo explica en 100 segundos:

- [Tailwind in 100 seconds - EN](https://www.youtube.com/watch?v=mr15Xzb1Ook)

Ahora ya podemos empezar a ver tutoriales de Tailwind :

- ***[Tutorial basico 10 minutos - EN](https://www.youtube.com/watch?v=pfaSUYaSgRo)***
- [Tutorial 0-100 15 minutos - ES](https://www.youtube.com/watch?v=Nj-wcVn3XgU)

**Comment by 22Noel** [comment]
I think we figured it out by now xd
