### ISSUE TITLE
[DOC] Review Documentation

### ISSUE THREAD

**Issue by uo288524** [Arquisoft/wiq_es1c#79]
Para llevar a cabo la revisión de la documentación cada participante revisará los 4 apartados siguientes a los que le tocó realizar.
En caso de haber realizado el apartado 1 y 2 revisará el 3, 4, 5 y 6 y así progresivamente. De esta forma todos los apartados serán revisados por 2 personas.

**Comment by 22Noel** [comment]
Revisados 5, 6, 7 y 8

**Comment by Manueluz** [comment]
7, 8 , 9 and 10 reviewed.

**Comment by uo288524** [comment]
Revisados 10, 11, 1 y 2.

**Comment by gs-Manuel** [comment]
Reviewed 3, 4, 5 and 6

**Comment by RubenFern** [comment]
Revisados 1, 2, 3 y 4

**Comment by Manueluz** [comment]
All reviewed!
