### ISSUE TITLE
[DOC] Documentation revision

### ISSUE THREAD

**Issue by uo288524** [Arquisoft/wiq_es1c#90]
- Delete section comments
- Add RTVE as a stakeholder
- Check ADR links
- Check 11 section title
- Change teacher surname
- Change stakeholder to wikimedia deutschland
- Add web application constraint
- Wikidata provides information for the questions (3.1)
- Unify 3.1 and 5.1 diagrams
- Edit 5.2 diagram
- Add the title to the ADRs in doc
- Modify table in section 3.2 to include inputs and outputs instead of descriptions

**Comment by 22Noel** [comment]
- Delete section comments

**Comment by 22Noel** [comment]
- Modify diagram in section 3.1

**Comment by 22Noel** [comment]
- Update section 5 diagrams so each microservice has its database, care with double direction arrows

**Comment by 22Noel** [comment]
Teacher surname, delete section comments and wikidata provides information for the questions.
All done in 'doc-corrections' branch

**Comment by 22Noel** [comment]
All done except table from 3.2
