### ISSUE TITLE
[APP] Game microservice

### ISSUE THREAD

**Issue by uo288524** [Arquisoft/wiq_es1c#97]
Elaborate the game microservice.

**Comment by Manueluz** [comment]
Began working on it

**Comment by Manueluz** [comment]
Basic functionality done, remaining tasks are:

- Tests
- Better handling of the game state
- Add timeout (and time limit)

**Comment by Manueluz** [comment]
Timeout added, im working on tests rn

**Comment by Manueluz** [comment]
Pull request merged into develop branch
